/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProGAL_geom3d_delaunay_Primitives */

#ifndef _Included_ProGAL_geom3d_delaunay_Primitives
#define _Included_ProGAL_geom3d_delaunay_Primitives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProGAL_geom3d_delaunay_Primitives
 * Method:    exactinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ProGAL_geom3d_delaunay_Primitives_exactinit
  (JNIEnv *, jobject);

/*
 * Class:     ProGAL_geom3d_delaunay_Primitives
 * Method:    insphere
 * Signature: (DDDDDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ProGAL_geom3d_delaunay_Primitives_insphere
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ProGAL_geom3d_delaunay_Primitives
 * Method:    orient3d
 * Signature: (DDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ProGAL_geom3d_delaunay_Primitives_orient3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ProGAL_geom3d_delaunay_Primitives
 * Method:    tetcircumradius
 * Signature: (DDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ProGAL_geom3d_delaunay_Primitives_tetcircumradius
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ProGAL_geom3d_delaunay_Primitives
 * Method:    tricircumradius3d
 * Signature: (DDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ProGAL_geom3d_delaunay_Primitives_tricircumradius3d
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ProGAL_geom3d_delaunay_Primitives
 * Method:    inspheretri
 * Signature: (DDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_ProGAL_geom3d_delaunay_Primitives_inspheretri
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
